### ISSUE TITLE
print explicit imports for current module

### ISSUE THREAD

**Issue by jariji** [ericphanson/ExplicitImports.jl#13]
Just a thought. So you don't have to mention which module it is:
```jl
macro print_explicit_imports()
  :($print_explicit_imports($(esc(@__MODULE__)))
end

**Comment by ericphanson** [comment]
Going to close this; I can see the motivation with examples like `print_explicit_imports(ExplicitImports)`, but common usage will be calling functions like `print_explicit_imports` from Main about packages loaded in their namespace, in which case I don't think this can help with.
