### ISSUE TITLE
Extension to ```runtests.jl``` in the /test dir

### ISSUE THREAD

**Issue by ctkelley** [ericphanson/ExplicitImports.jl#19]
This package is great stuff. Is there a way to run it on the ```runtests.jl``` script you use for CI?

**Comment by ericphanson** [comment]
Yep! You can add it as a test dependency, and then use these functions in your tests: https://ericphanson.github.io/ExplicitImports.jl/stable/api/#Usage-in-testing

**Comment by ctkelley** [comment]
That's not exactly what I had in mind. My ```runtests.jl``` file is not a module, but begins with several ```using``` statements. Can I figure out what the implicit imports in my test suite are?

**Comment by ericphanson** [comment]
Ah I see. You could try: `print_explicit_exports(Main, "test/runtests.jl")`. Let me know if that works, maybe we can document it or add a shortcut for main.

**Comment by ctkelley** [comment]
Thanks!

I assume you meant

```
print_explicit_imports(Main, "test/runtests.jl")
```
That did the job, but then I got complaints about Base.  Several lines of stuff like this.
```
Module Base is not relying on any implicit imports.

Module Base.GMP.MPQ is not relying on any implicit imports.

Module Base.StackTraces is not relying on any implicit imports.

Module Base.__toplevel__ is not relying on any implicit imports.

Module Base.Ryu is not relying on any implicit imports.
```

**Comment by ericphanson** [comment]
Ok good to know, we can probably provide a “script” entry point that can filter stuff like that out and be usable for this

**Comment by ericphanson** [comment]
The reason Base shows up is basically https://github.com/JuliaLang/julia/issues/53574. But we can filter it out manually.

**Comment by ericphanson** [comment]
v1.2 is out with `print_explicit_imports_script` that should cover this! Let me know if you run into issues.

**Comment by ctkelley** [comment]
That did the job. Thanks for responding to this so fast.
