### ISSUE TITLE
modules exporting names which aren't theirs

### ISSUE THREAD

**Issue by baggepinnen** [ericphanson/ExplicitImports.jl#29]
Here's a fun one

`UUID` belongs to base
```
julia> parentmodule(Base.UUID)
Base
```
but is not exported by Base
```
julia> UUID
ERROR: UndefVarError: `UUID` not defined
```
However, it is exported by UUIDs
```
julia> using UUIDs

julia> UUID
UUID

julia> parentmodule(UUID)
Base
```

When running ExplicitImports on ControlSystemsBase, I got
```
using UUIDs: UUIDs
```
which then makes `UUID` no longer imported by CSBase and tests are failing. Would there be a way to detect this happening?

**Comment by ericphanson** [comment]
ah yeah, this is tricky. I think https://github.com/ericphanson/ExplicitImports.jl/pull/28 could help here. In that PR I track things a bit better so I think I could handle this.
