### ISSUE TITLE
Feature request: Reexport compatibility

### ISSUE THREAD

**Issue by MilesCranmer** [ericphanson/ExplicitImports.jl#69]
Awesome package!

Feature request: I'm not sure this is even possible (and it's not a big deal either way) but I wonder if `@reexport` could be skipped over? Right now the following code

```julia
module MyLibrary
@reexport import .MyInternalModule: foo
...
end
```

will flag `foo` as a stale explicit import even though `foo` is exported.

**Comment by ericphanson** [comment]
interesting, we currently rely on parsing the raw `export foo` statements to notice that `foo` is being used. I think we could detect exports programmatically (via `names` + `Base.isexported`) and automatically mark them as non-stale.

**Comment by MilesCranmer** [comment]
That sounds good to me. If it makes things simpler I think it's probably fine to just add special behavior for `@reexport`. I don't know of any other tools which perform an `export` via a macro so the general case might not be worth it.

**Comment by ericphanson** [comment]
special casing would be harder actually, since that involves modifying the hairy parsing stuff. Doing it at the dynamic level is a lot easier in fact

**Comment by MilesCranmer** [comment]
Awesome, that was fast!! 😃
