### ISSUE TITLE
ExplicitImports has a colliding implicit import: `parse`

### ISSUE THREAD

**Issue by palday** [ericphanson/ExplicitImports.jl#77]
And this leads to a warning for a shared export between JuliaSyntax and Base.

**Comment by ericphanson** [comment]
Yeah: https://github.com/ericphanson/ExplicitImports.jl?tab=readme-ov-file#example. I am calling `which` on every name in the module, so even if it is unused in that module, it will warn.

**Comment by palday** [comment]
Incidentally, that behavior is one of the reasons for a mutual colleagues stance on collisions and the necessity of all sorts of warnings and behaviors around them.
